name: Tengying Camera Bridge
version: 0.7.1
slug: tengying_bridge
description: 腾影智联摄像头 PPCS 收流桥（双镜头 4 路 RTSP + PTZ + 双向语音 + 云端录像）
url: https://github.com/C3H3-AI/ha-tengying-camera
arch:
  - aarch64
init: false
host_network: true
privileged:
  - SYS_ADMIN
full_access: true
apparmor: disable
startup: application
boot: auto
options:
  username: ""
  password: ""
  devices:
    - ""
  rtsp_port: 8560
schema:
  username: str
  password: password
  devices:
    - str
  rtsp_port: int
